### ISSUE TITLE
Vimtex support isn't complete

### ISSUE THREAD

**Issue by jfab-123** [hrsh7th/cmp-omni#1]
When I go in a .tex file, I want omni completion so I can use vimtex omni suggestions to my advantage. When I type \a for example, the suggestions are correct and I get this: 

![image](https://user-images.githubusercontent.com/81712003/139907403-ace6b4f7-87c0-45b6-9c20-a57ad9878eb2.png)

However with some letters, some completion is missing. For example if I type \b I get:
![image](https://user-images.githubusercontent.com/81712003/139907559-497a281a-602a-4610-a20d-6bb084870736.png)

Which is missing a LOT of omni completions. For example \beta, or \backslash. If I type ```<c-x><c-o>``` with \b I get:
![image](https://user-images.githubusercontent.com/81712003/139907647-bd84fb6a-0f40-438c-8ac9-82fcb9c5979a.png)
And I dont get any of that with nvim-cmp
I have noticed the same problem with \s, \e, and a lot of other letters. For example \p *does* include all the options from the omni completion, but this varies from time to time. 

This is my init.vim:
```vim
call plug#begin()
Plug 'lervag/vimtex' 
Plug 'hrsh7th/nvim-cmp'
Plug 'SirVer/ultisnips'

"nvim-cmp sources
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-omni'
Plug 'hrsh7th/cmp-path'
Plug 'hrsh7th/cmp-cmdline'
Plug 'quangnguyen30192/cmp-nvim-ultisnips'

call plug#end()
lua <<EOF
  -- Setup nvim-cmp.
  local cmp = require'cmp'

  cmp.setup({

    snippet = {
      expand = function(args)
        vim.fn["UltiSnips#Anon"](args.body) 
      end,
    },

    mapping = {
         ['<C-n>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Insert }),
         ['<C-p>'] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Insert }),
    },

    sources = cmp.config.sources({
      { name = 'ultisnips' }, 
      { name = 'omni' }, 
      { name = 'buffer' },
    })

  })

  -- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline('/', {
    sources = {
      { name = 'buffer' }
    }
  })

  cmp.setup.cmdline(':', {
    sources = cmp.config.sources({
      { name = 'path' }
    }, {
      { name = 'cmdline' }
    })
  })

EOF ```

**Comment by jhossbach** [comment]
@hrsh7th The offset in this line is wrong:
https://github.com/hrsh7th/cmp-omni/blob/3fec8a57d6d230c81d24c03dd80e97c62d4eda63/lua/cmp_omni/init.lua#L20
`offset` should be `offset + 1`.  If the current line says `\b` for example, only the `b` has to be passed to the omnifunc. For some characters it still works (e.g. `\B`). For @jfab-123 the results displayed are only those items from the buffer / ultisnips.

**Comment by jhossbach** [comment]
The vimtex omnifunc also provides additional data, e.g. symbols as seen in the picture above, or additional information when using `\cite{...`. I will try to come up with an extra source to include this as well.

**Comment by hrsh7th** [comment]
I think it's keyword pattern problem. What the keyword pattern did you use?

@jhossbach

**Comment by jhossbach** [comment]
Let me illustrate on the example `\b`:
I believe vimtex's omnifunc expects `b` to be passed, but I believe as of now, `\b` is passed (or maybe its an escape issue and it should be `\\b`?).
I tested this using
```lua
:lua print(vim.inspect(vim.api.nvim_call_function(vim.bo.omnifunc, {0, 'b'})))`
```
with omnifunc begin set to `vimtex#complete#omnifunc`

**Comment by hrsh7th** [comment]
Oh my... The omnifunc should reutnr the number that 0-origin indexed...

OK. I think it should be +1 value. @jhossbach Is there something wrong?

**Comment by hrsh7th** [comment]
```

function! OmniFuncTest(findstart, input) abort
  if a:findstart == 1
    return 1
  end
  return ['foo', 'bar', 'baz']
endfunction
set omnifunc=OmniFuncTest
```

I tested with the above example omnifunc.

If I return `0` as start position, the completion menu will be shown to `1 column`.
If I return `1` as start position, the completion menu will be shown to `2 column`.

**Comment by jhossbach** [comment]
I am unsure, seeing that vimtex seems to work flawlessly with other plugins such as `deoplete` etc.

**Comment by hrsh7th** [comment]
I've fixed the offset problem. Thank you very much.

**Comment by hrsh7th** [comment]
At least, the html omnifunc is worked fine with this fix.

**Comment by jhossbach** [comment]
Great, glad to help! On a side note, vimtex provides a lot of additional data that is currently not displayed in nvim-cmp. Can we add that to the list of items to show? Or should we add another source explicitly for vimtex? See this comment: https://github.com/lervag/vimtex/issues/2215#issuecomment-981784450

**Comment by jhossbach** [comment]
This is a sample output for the pattern `b`, we could add these entries to also display in the completion window.

![image](https://user-images.githubusercontent.com/50084485/143916332-81d0e1b4-ecef-4c69-a8b8-5770db2bb92d.png)

**Comment by jfab-123** [comment]
> I've fixed the offset problem. Thank you very much.

I think this works for me!

**Comment by hrsh7th** [comment]
@jhossbach I've added the `kind` and `menu`.

**Comment by jhossbach** [comment]
Ah, very nice, I did not know about `LabelDetails`, looks good to me! I think this can be closed now

**Comment by hrsh7th** [comment]
FYI: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItemLabelDetails

Thank you for all.

**Comment by Xystel** [comment]
Is it possible to format the menu of nvim-cmp, without loosing the additional information provided by vimtex?

I've followed the steps described [here](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#basic-customisations) to customize my menu with lspicons. 

At the moment my `vim_item.menu` looks like this:

```
-- set a name for each source
vim_item.menu = ({
    nvim_lsp = "[LSP]",
    luasnip = "[LuaSnip]",
    buffer = "[Buffer]",
    omni = "[Omni]",
    path = "[Path]",
    latex_symbols = "[Latex]",
})[entry.source.name]
```
In my menu appears `[Omni]` instead of the `LabelDetails`, e. g. `[cmd: default]`. But I would like to have both information. Is this possible?
