### ISSUE TITLE
Support replacement offest

### ISSUE THREAD

**Issue by alerque** [hrsh7th/cmp-omni#7]
One thing many legacy omnicomplete functions do is return a position for the start of the completion as well as an array of possible items. I've taken a few stabs at wiring up a legacy omni complete function to *cmp* without much luck. I got pretty close by setting `keyword_patterm = [[.*]]` and stuffing everything that the complete function can touch into vim's `iskeyword` setting, but it's still clunky.

According to [this comment](https://github.com/hrsh7th/nvim-cmp/issues/1127#issuecomment-1214407590) the `textEdit` property might offer a solution, but I have no idea where to start.

It seems to me like this plugin should offer a way to shim the two so that omni complete functions can be a dropin source even if they return results that don't start at the beginning of the current keyword (which seems to be *cmp*'s assumption).

**Comment by lervag** [comment]
I'm hitting this exact thing right now and was about to open an issue to get some pointers on where to start addressing this. As an example, I have an omni completion function for my wiki (https://github.com/lervag/wiki.vim/blob/master/autoload/wiki/complete.vim) - it works well with nvim-cmp in most cases, except it has an offset issue. Notice, first autocompleting and selecting the first without space characters:

![image](https://user-images.githubusercontent.com/998898/199840991-55886e2b-1ee9-4127-9c51-8b6c7cbe14fb.png) ![image](https://user-images.githubusercontent.com/998898/199841063-82c36b2c-dc32-4666-bc81-c45d0fb95fe3.png)

Now use the space character, and the offset is off:

![image](https://user-images.githubusercontent.com/998898/199841188-99175799-a141-4ccd-9918-86413171a9f9.png) ![image](https://user-images.githubusercontent.com/998898/199841208-f35e0aec-baff-4dba-ad05-4441d86eaa84.png)

The omnifunc reports the correct offset here:

https://github.com/hrsh7th/cmp-omni/blob/7a457f0c4f9e0801fee777d955eb841659aa3b84/lua/cmp_omni/init.lua#L15-L19

However, it seems there is no way to pass this offset back to the handler. This looks partly relevant:

https://github.com/hrsh7th/cmp-omni/blob/7a457f0c4f9e0801fee777d955eb841659aa3b84/lua/cmp_omni/init.lua#L42-L49

Except in the present situation, `params.offset > offset_0 + 1`.

I'll be more than glad to help with a PR here, but some some advice on where to start would be very helpful!

**Comment by ModProg** [comment]
Would a solution maybe be to truncate the returned completions to only contain the last word?

**Comment by ModProg** [comment]
I just updated but now get this error:
```
Error executing vim.schedule lua callback: ...e/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/entry.lua:548: attempt to index
 local 'position' (a nil value)
stack traceback:
        ...e/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/entry.lua:548: in function 'convert_position_encoding'
        ...e/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/entry.lua:320: in function 'get_insert_range'
        ...e/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/entry.lua:61: in function 'callback'
        .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/cache.lua:38: in function 'get_offset'
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:348: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
 
```

**Comment by lervag** [comment]
Thanks, it works! :D
