### ISSUE TITLE
Completion is auto selected when omni source is used

### ISSUE THREAD

**Issue by wangl-cc** [hrsh7th/cmp-omni#8]
Sorry about my bad description. More about this issue, please have a look at the screen recording. When I type a character, then a completion is selected immediately, and also there are two popup.

https://user-images.githubusercontent.com/40141251/203274346-2b7c094e-09ec-4632-82e2-4c5a5a8fd38b.mov

Minimal `init.lua` to Reproduce this issue:
```lua
require("packer").startup({
  {
    "wbthomason/packer.nvim",
    "hrsh7th/nvim-cmp",
    "hrsh7th/cmp-nvim-lsp",
    "hrsh7th/cmp-omni",
    "neovim/nvim-lspconfig",
  },
})

local cmp = require("cmp")
local cmp_lsp = require("cmp_nvim_lsp")
local lspconfig = require("lspconfig")
lspconfig.sumneko_lua.setup {
  cmd = { "lua-language-server" },
  settings = {
    Lua = {
      telemetry = { enable = false },
    },
  },
  capabilities = cmp_lsp.default_capabilities(),
}
cmp.setup {
  sources = cmp.config.sources({
    { name = "nvim_lsp" },
  }, {
    { name = "omni" },
  })
}
```

**Comment by liuyuzhenn** [comment]
I have the issue

**Comment by p00f** [comment]
It looks like it is using the lsp omnifunc (and hence if you select LSP snippets they are weird) ? If you `set omnifunc=` after the server has attached it fixes the issue

**Comment by p00f** [comment]
I worked around this by doing `set vim.bo.omnifunc = ""` in my lsp on_attach

**Comment by bstaint** [comment]
It's conflict with nvim_lsp, temporary solution.
```
local on_attach = function(client, bufnr)
  -- https://github.com/neovim/neovim/pull/19677
  -- https://github.com/hrsh7th/cmp-omni/commit/01f0f66e7dc227606bb8d8ffad688b9c393a052c
  vim.api.nvim_buf_set_option(bufnr, "omnifunc", "any non-empty character")
end
```

**Comment by p00f** [comment]
@bstaint  It happens in python's omnifunc and I don't have lsp configured for python

**Comment by kwand** [comment]
@hrsh7th Any idea what is causing this issue (and if it indeed due to `nvim_lsp` conflicts whether some note should be made about this in the README itself?)

I believe you worked with @lervag over at the `vimtex` when they were implementing support for nvim-cmp via omni? (I see some commits on this repo were made due to issues discussed over at vimtex). Is this a new issue, or did it happen before?

**Comment by cnrrobertson** [comment]
I think the autoselection can be avoided with the vim setting `vim.opt.completeopt:append('noselect')` but the multiple popups are still unresolved

**Comment by keiwanjamaly** [comment]
> It's conflict with nvim_lsp, temporary solution.
> 
> ```
> local on_attach = function(client, bufnr)
>   -- https://github.com/neovim/neovim/pull/19677
>   -- https://github.com/hrsh7th/cmp-omni/commit/01f0f66e7dc227606bb8d8ffad688b9c393a052c
>   vim.api.nvim_buf_set_option(bufnr, "omnifunc", "any non-empty character")
> end
> ```

@bstaint Since this is already open for a while, what have you done with `on_attach`?
